### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by ryan190123** [Digressive/WSUS-Maintenance#1]
WSUS maintenance routine starting...
Invoke-WsusServerCleanup : Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
The statement has been terminated.
At C:\temp\Wsus-Maintenance.ps1:126 char:62
+     Get-WsusServer -Name $WsusServer -PortNumber $WsusPort | Invoke-WsusServerCl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Updat...rCleanupCommand:InvokeWsusServerCleanupCommand) [Invoke-WsusServerCleanup], SqlException
    + FullyQualifiedErrorId : UnexpectedError,Microsoft.UpdateServices.Commands.InvokeWsusServerCleanupCommand

**Comment by Digressive** [comment]
Hi,

This is more of a problem with WSUS timing out. Best thing to do is reset the services (or better yet reboot the whole server) and run the script again multiple times until it completes successfully. On a poorly maintained WSUS server it can take a long time to clean up.
